# Generated by Django 3.2.5 on 2021-07-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210704_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_teacher',
            field=models.BooleanField(),
        ),
    ]
